module: "sokol.log"
language: "c"
headers:
  - "deps/sokol/sokol_log.h"
include_paths:
  - "deps/sokol"
defines: []
prefix: "slog_"
output:
  c_binding: "gen/bindings/sokol_log.c"
  types: "gen/types/sokol/log.lua"
rules:
  allow_out_params: true
  callback_support: false
  strict_validation_default: "strict"
overrides:
  allow:
    - "^slog_.*$"
