module: "sokol.glue"
language: "c"
headers:
  - "deps/sokol/sokol_glue.h"
include_paths:
  - "deps/sokol"
defines: []
prefix: "sglue_"
output:
  c_binding: "gen/bindings/sokol_glue.c"
  types: "gen/types/sokol/glue.lua"
rules:
  allow_out_params: true
  callback_support: false
  strict_validation_default: "strict"
overrides:
  allow:
    - "^sglue_.*$"
