module: "sokol.shape"
language: "c"
headers:
  - "deps/sokol/util/sokol_shape.h"
include_paths:
  - "deps/sokol"
  - "deps/sokol/util"
defines: []
prefix: "sshape_"
output:
  c_binding: "gen/bindings/sokol_shape.c"
  types: "gen/types/sokol/shape.lua"
rules:
  allow_out_params: true
  callback_support: false
  strict_validation_default: "strict"
overrides:
  allow:
    - "^sshape_.*$"
